version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-backend-python"
s3_prefix = "aws-backend-python"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
